[workspace]
members = ["server", "interfaces/hashing", "plugins/fx-plugin", "plugins/xx-plugin"]
resolver = "3"

[workspace.package]
authors = ["Raif S. Naffah <raif@mailbox.org>"]
edition = "2024"
repository = "https://github.com/raif-s-naffah/wasm-plugins"
license = "GPL-3.0-or-later"
keywords = ["PoC", "WASM", "WASIp1", "Plugin"]
categories = ["runtime-plugins", "rust-patterns", "wasm"]

[workspace.dependencies]
# hashing = { path = "interfaces/hashing" }
hashing = { version = "0.1.0", path = "interfaces/hashing" }
wasmtime = "46.0.1"
wasmtime-wasi = "46.0.1"

[profile.release]
opt-level = "z"
lto = true
strip = true
