[package]
name = "fx-plugin"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hashing = { workspace = true }
fxhash = "0.2.1"
paste = { workspace = true }

[lib]
crate-type = ["cdylib"]
