[package]
name = "server"
description = "Example server/app using WASM plugins"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hashing = { workspace = true }
thiserror = "2.0.21"
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
