[package]
name = "xx-plugin"
description = "Hashing implementation using twox-hash"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hashing = { workspace = true }
twox-hash = { version = "2.1.2", default-features = false, features = ["xxhash32", "std"] }

[lib]
crate-type = ["cdylib"]
