[package]
name = "xx-plugin"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hashing = { workspace = true }
twox-hash = { version = "2.1.2", default-features = false, features = ["xxhash32", "std"] }
paste = { workspace = true }

[lib]
crate-type = ["cdylib"]
